# Usa una imagen base de Linux que ya tenga Python instalado
# 'python:3.10-slim' es una base ligera y estable
FROM python:3.10-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requisitos e instálalo primero
# Esto mejora la caché de Docker
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de la aplicación (el sistema de membresía y los tests)
COPY . .

# Comando por defecto para ejecutar las pruebas (aunque Jenkins lo sobrescribirá)
CMD ["pytest"]
